import { Header } from '@/components/header';
import { Footer } from '@/components/footer';

export default function AboutPage() {
    return (
        <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-1 pt-20 px-4 max-w-4xl mx-auto w-full">
                <h1 className="text-3xl font-bold mb-6">About Legendary Investor</h1>
                <p className="mb-4">
                    Legendary Investor is an AI-powered financial analysis tool that lets you view your portfolio through the lens of history's greatest investors.
                </p>
                <p className="mb-4">
                    Our AI simulates the investment frameworks of Warren Buffett, Charlie Munger, Michael Burry, Peter Lynch, and Stanley Druckenmiller to provide diverse, contrarian, and educational perspectives on your holdings.
                </p>
                <div className="p-4 border-2 border-foreground mt-8 bg-muted/20">
                    <h3 className="font-bold mb-2">Disclaimer</h3>
                    <p className="text-sm text-muted-foreground">
                        This application is for educational and entertainment purposes only. The "analysis" is generated by AI based on public personas and does not constitute financial advice. Always do your own research.
                    </p>
                </div>
            </main>
            <Footer />
        </div>
    );
}
